workflows:
  android-release:
    name: Android Release Build
    environment:
      flutter: stable
      vars:
        KEYSTORE_PASSWORD: Encrypted:YOUR_KEYSTORE_PASSWORD
        KEY_PASSWORD: Encrypted:YOUR_KEY_PASSWORD
        KEY_ALIAS: my-key-alias
        KEYSTORE_FILE: $CM_BUILD_DIR/android/my-release-key.jks
    scripts:
      # 1️⃣ Install dependencies
      - name: Get Flutter packages
        script: flutter pub get

      # 2️⃣ Prepare key.properties for signing
      - name: Generate key.properties
        script: |
          echo "storePassword=$KEYSTORE_PASSWORD" > android/key.properties
          echo "keyPassword=$KEY_PASSWORD" >> android/key.properties
          echo "keyAlias=$KEY_ALIAS" >> android/key.properties
          echo "storeFile=$KEYSTORE_FILE" >> android/key.properties

      # 3️⃣ Build release APK
      - name: Build release APK
        script: flutter build apk --release --no-shrink

      # 4️⃣ Build release AAB (optional for Play Store)
      - name: Build release AAB
        script: flutter build appbundle --release --no-shrink

    artifacts:
      # APK for direct installation
      - build/app/outputs/flutter-apk/app-release.apk
      # AAB for Play Store
      - build/app/outputs/bundle/release/app-release.aab
