name: wireless_appf
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0
  
dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  fl_chart: ^0.68.0
  percent_indicator: ^4.2.3
  csv: ^6.0.0
  file_picker: ^6.1.1
  intl: ^0.19.0   # ✅ Add this


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
